---
kind: pipeline
name: drone-plugin
steps:
  - name: release
    settings:
      image: plugins/docker
      registry: lowess
      repo: ${DRONE_REPO_NAME}
      tags:
        - ${DRONE_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      when:
        event: tag
